export class Person{
	private surname:string;
	private name: string;
	private patername:string;
	private birthday:string;
	private nameInDativeForm:string;
	private educational_establishment:number;
	private cityzenship:number;
	private isDoctor:boolean;
	private isCowoker:boolean;
	private isMale:boolean;
	private diploma_start: string;
	private organization:number;
	private appointment:number;
	private region:number;
	private tel_number:string;
	private experiance_general:number;
	private experiance_special:number;
	private insurance_number:string;
	private department:number;
	private faculty:number;
	private diploma_number:string;
	private belmapo_faculty:number;
	private belmapo_cathedra:number;
	private belmapo_course:number;
	private belmapo_educType:number;
	private belmapo_residense:number;
	private belmapo_educForm:number;
	private belmapo_paymentData:number;
	private belmapo_docNumber:string;

	constructor(){
		this.surname = "Товпинец";
		this.name = "Кирилл";
		this.patername = "Александрович";
		this.birthday = "1994-02-10";
		this.nameInDativeForm = "Товпинцу Кириллу Александровичу";
		this.educational_establishment = 1;
		this.cityzenship = 1;
		this.isDoctor = true;
		this.isCowoker = true;
		this.isMale = true;
		this.diploma_start = "2017-01-01";
		this.organization = 1;
		this.appointment = 1;
		this.region = 1;
		this.tel_number = "1111111111111111111111111111111";
		this.experiance_general = 1;
		this.experiance_special = 1;
		this.insurance_number = "1111111111111111111111111111111";
		this.department = 1;
		this.faculty = 1;
		this.diploma_number = "1111111111111111111111111111111";
		this.belmapo_faculty = 1;
		this.belmapo_cathedra = 1;
		this.belmapo_course = 1;
		this.belmapo_educType = 1;
		this.belmapo_residense = 1;
		this.belmapo_educForm = 1;
		this.belmapo_paymentData = 1;
		this.belmapo_docNumber = "2134556";
	}
}